version: '3.8'

services:
  interpreter:
    build:
      context: ./interpreter
    volumes:
      - ./interpreter/app:/app
    environment:
      - INTERPRETER_CLI_AUTO_RUN=${INTERPRETER_CLI_AUTO_RUN}
      - INTERPRETER_CLI_FAST_MODE=${INTERPRETER_CLI_FAST_MODE}
      - INTERPRETER_CLI_LOCAL_RUN=${INTERPRETER_CLI_LOCAL_RUN}
      - INTERPRETER_CLI_DEBUG=${INTERPRETER_CLI_DEBUG}
      - OPENAI_API_KEY=${OPENAI_API_KEY}